@ECHO off
ECHO Clearing build directory...
DEL /F /S /Q build
ECHO Copying to build directory...
ROBOCOPY .\ build /E /XD build /XF .gitignore
ECHO Jumping into build directory...
CD build
ECHO Running NPM install...
CMD /C npm install
ECHO Initializing new single-commit repo...
git init
git checkout -B gh-pages
git add .
git commit -m "Built"
ECHO Configuring git credential helper...
git config --global credential.helper store
ECHO Pushing to remote repo...
git remote set-url origin https://github.com/matthew-a-thomas/api-consulting-and-investigations.git
REM Make sure you have the latest version of this or you might get `HttpRequestException` due to "Could not create SSL/TLS secure channel": https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases
git push -u --force origin gh-pages
ECHO Done!
cd ..